version: '3.9'

services:
  zookeeper:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    restart: always
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - fundamental-network

  kafka:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: always
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 100
    networks:
      - fundamental-network

  database:
#    image: bitnami/cassandra:latest
    image: cassandra:4
    ports:
      - "9042:9042"
    restart: always
    environment:
#      - CASSANDRA_HOST=database
      - CASSANDRA_DATACENTER=datacenter1
#      - CASSANDRA_SEEDS=database
#      - CASSANDRA_PASSWORD_SEEDER=yes
#      - CASSANDRA_PASSWORD=cassandra
#      - CASSANDRA_USER=cassandra
    volumes:
      - ./cassandra:/docker-entrypoint-initdb.d
    networks:
      - fundamental-network

  employee:
    image: thaso-example/employee:1.0
    build:
      context: employee
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - kafka
      - database
    ports:
      - "8081:8080"
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - fundamental-network

  worktime:
    image: thaso-example/worktime:1.0
    build:
      context: worktime
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - kafka
      - database
    ports:
      - "8082:8080"
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - fundamental-network

networks:
  fundamental-network:
    name: funet
